name: Build binary
'on':
  push:
  pull_request:
    branches:
      - '**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
          if [ "${{ github.event.pull_request.base.ref }}" = "master" ]; then cd mintbase-near-indexer && git checkout dev && cd simple-market-contract && git checkout dev && cd ../; fi
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo +nightly fmt -- --check && cargo lint
